【確認待ち】GTag対応
vektor-inc/biz-vektor pull request #327
Opened 2024-03-23 13:50 UTC by mthaichi

GA4に対応できるようGA設定の部分を変更しました。

- 「Gtag」を選択できるようにした。
- 設定値が「G-」「UA-」から始まらない場合は、前に「UA-」をつけたものをIDとする
- 設定値が「G-」「UA-」から始まる場合は、その文字列をIDとする。

2024-03-23 19:04 UTC, kurudrive requested changes
@mthaichi ありがとうございます。
ここって エスケープしておいた方が良いですよね？
元がしてなかったですけど...

2024-03-23 19:04 UTC, kurudrive commented on plugins/seo_and_ga/seo_and_ga.php
> +			_gaq.push(['_setAccount', '<?php echo $gtag_id; ?>']);
```suggestion
			_gaq.push(['_setAccount', '<?php echo esc_html( $gtag_id ); ?>']);
```

2024-03-23 19:04 UTC, kurudrive commented on plugins/seo_and_ga/seo_and_ga.php
> +			ga('create', '<?php echo $gtag_id; ?>', '<?php echo $domain; ?>');
```suggestion
			ga('create', '<?php echo esc_html( $gtag_id ); ?>', '<?php echo esc_html( $domain ); ?>');
```

2024-03-25 10:39 UTC, mthaichi commented
@kurudrive ありがとうございます。おっしゃるとおりでした。
もう一箇所あったので、追加でesc_html 入れました！

2024-03-26 12:08 UTC, kurudrive approved these changes

2024-03-26 12:09 UTC, kurudrive commented
@mthaichi ありがとうございまっすー。

<img width="184" alt="スクリーンショット 2024-03-23 10 46 32" src="https://github.com/vektor-inc/biz-vektor/assets/3272660/823921ef-b81c-4e21-9747-9982269098d0">

2024-03-26 12:09 UTC, merged

2024-03-26 12:12 UTC, kurudrive commented
@mthaichi もうこの段階で一旦リリースで良いですよね（・ｗ・？